services:
  pdf2zh-md:
    image: ghcr.io/cjl196/pdf2zh-md:latest
    container_name: pdf2zh-md
    ports:
      - "7860:7860"
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file: .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    network_mode: host