name: app

on:
  push:
    branches: [ "master", "main", "ci" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
    paths: ["app/**"]
  pull_request:
    # branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pdf2zh-md

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha,enable=${{ !startsWith(github.ref, 'refs/tags/v') }},prefix=,suffix=,format=long
      - name: Build and push Docker image (untagged)
        uses: docker/build-push-action@v4
        if:  ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (tagged)
        uses: docker/build-push-action@v4
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Prune old packages
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          container: ${{ env.IMAGE_NAME }}
          dry-run: false
          keep-last: 5
          keep-tags-regexes: ^v(.)*
          prune-tags-regexes: |
            ^[0-9a-f]{6,40}
            sha-*
            pr-*
          keep-tags: |
            latest
          prune-untagged: true